logo_title: VLADIMIR KRYZHANOVSKYI

style: black

favicon: /favicon.ico

menu:
  project: /project
  domain: /domain
  links: /links
  about: /about
  Github: https://github.com/vavas


valine:
  enable: true
  appId: CmCti21ooOOIzFOhEyFkFvR0-gzGzoHsz
  appKey: FqiyUqbg7McKN2eG0MCewupf

highlight:
  enable: false